name: Voxel.Wiki Site Generation

on:
  push:
    branches:
      - main 
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: 'Build Site'
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/main'
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
      - name: 'Disable Git Safety'
        run: |
          git config --global --add safe.directory '*'
          git config --global --add safe.directory /__w/{repo_name}/{repo_name}
          git config --global --add safe.directory /github/workspace
      - name: 'Build' 
        uses: shalzz/zola-deploy-action@37076cb04a796fdfbb66182375fd8b41a7f3a0e0
        env:
          BUILD_DIR: .
          BUILD_ONLY: true
          GITHUB_TOKEN: ${{ secrets.VOXEL_WIKI }}
  build_and_deploy:
    name: 'Build & Deploy Site'
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
      - name: 'Disable Git Safety'
        run: |
          git config --global --add safe.directory '*'
          git config --global --add safe.directory /__w/{repo_name}/{repo_name}
          git config --global --add safe.directory /github/workspace
      - name: 'Build & Deploy'
        uses: shalzz/zola-deploy-action@37076cb04a796fdfbb66182375fd8b41a7f3a0e0
        env:
          PAGES_BRANCH: gh-pages
          BUILD_DIR: .
          GITHUB_TOKEN: ${{ secrets.VOXEL_WIKI }}
